changelog:
  categories:
    - title: Features
      labels:
        - feature
        - feat
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Other Changes
      labels:
        - "*"
