[package]
name = "menvane-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "menvane"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
menvane-domain = { path = "../menvane-domain" }
menvane-engine = { path = "../menvane-engine" }
menvane-integrations = { path = "../menvane-integrations" }
menvane-server = { path = "../menvane-server" }
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
uuid.workspace = true
